UserBase:
  type: object
  properties:
    users:
      type: array
      items:
        $ref: '../../../schema/user.yaml#/UserV3'
    files:
      type: array
      items:
        $ref: '../../../schema/file.yaml#/File'

User:
  allOf:
    - type: object
      properties:
        id:
          type: string
          description: The user ID.
        data:
          $ref: '#/UserBase'
    - $ref: '../../../schema/realtime.yaml#/Wrapper'
