TargetId:
  type: string
  maxLength: 900

TargetType:
  type: string
  enum:
    - community
    - user

Targets:
  type: array
  items:
    type: object
    properties:
      targetId:
        $ref: "#/TargetId"
      targetType:
        $ref: "#/TargetType"
  maxItems: 10
  minItems: 1

DataType:
  type: string
  enum:
    - image
    - video

QueryOptions:
  type: object
  properties:
    sortBy:
      type: string
      default: createdAt
      enum:
        - createdAt
    orderBy:
      type: string
      default: desc
      enum:
        - asc
        - desc
    limit:
      type: integer
      default: 10
      minimum: 1
      maximum: 100
    token:
      type: string

StoryId:
  type: string
  pattern: '^[a-f\d]{24}$'

SeenState:
  type: string
  enum:
    - all
    - seen
    - unseen
  default: unseen