ChannelIds:
  type: array
  items:
    type: string
    description: list of channel id (internal)

ChannelId:
  type: string
  description: channel id (internal)

MessageFeedIds:
  type: array
  items:
    type: string
    description: list of message feed id (internal)

MessageFeedId:
  type: string
  description: message feed id (internal)

MessageIds:
  type: array
  items:
    type: string
    description: list of message id (internal)

