QueryOptions:
  type: object
  properties:
    sortBy:
      type: string
      default: createdAt
      enum:
        - createdAt
        - pinnedAt
        - updateddAt
    orderBy:
      type: string
      default: desc
      enum:
        - asc
        - desc