Wrapper:
  type: object
  properties:
    networkId:
      type: string
      description: ID of the network.
    path:
      type: string
      description: A topic path for subscription.
    eventType:
      type: string
      description: Name of the event.
    senderId:
      type: string
      description: ID of sender node.
    sendTime:
      type: string
      description: The date/time when event was sent.
      format: date-time
    version:
      type: string
      description: Version of API
