SortBy:
  name: sortBy
  in: query
  required: false
  description: > 
    Sort by option
      * customRanking: Sort by custom ranking
      * lastCreated: Sort by last created
  schema:      
    type: string
    enum:
      - createdAt
      - customRanking
    default: customRanking