name: bump and publish

on:
  workflow_dispatch:
    inputs:
      release:
        description: "release type"
        type: choice
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install deps
        run: npm install --frozen-lockfile

      - name: changelog
        run: npm run changelog:gen

      - name: bump version
        run: |
          npm version ${{ github.event.inputs.release }}
