name: publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'chore-bump-')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          version=$(jq -r .version package.json)
          echo "tag version: $version"
          git tag $version
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $version
